### ISSUE TITLE
dist/index.min.js cannot be used whatsoever with keyword Import or Import() function.

### ISSUE THREAD

**Issue by kthewhispers** [ipfs/js-datastore-fs#147]
**Assuming I am importing the right file to get the class from the package.**

Running 8.0.0 here.

I'm using a Node.js environment, and my specific use-case requires a unique infastructure. My Node project cannot be a module type as it's Electron + Node.js.

I insist on using node modules in the renderer as the app doesn't expose security risks or take any sensitive data as input ever. 

**Node Integration is on completely in my environment. If I copy paste your usage code in readme.md then hook it up to the dist/index.min.js in the node package for my project it says the class doesnt exist.
When I tried to do the src index.js it was saying the way importing was done was wrong syntax**
**

Anyway. I've tried importing the src/ index.js and it says the imports inside aren't specified correctly for 'fs' etc

Import with keyword src index.js and even the dist/index.min.js:
My call is correct and exactly done per the usage in readme.md. When it goes to read the script the error is like:
`Relative references must start with either "/", "./", or "../".`

Consider this line of code. This should work:
`let { FSDatastore } = await import('../node_modules/datastore-fs/dist/index.min.js');`
Alternatively I tried this.
`await import('../node_modules/datastore-fs/dist/index.min.js');`

Regardless of doing it these ways.. Upon reading that line the catch() spits out:
`TypeError: (0 , $n.promisify) is not a function
    at index.min.js:19:6732
    at index.min.js:19:9847
    at index.min.js:1:107
    at index.min.js:1:148`

**It would seem that the module itself has syntax errors**

_I should be able to use import() to get this into a non-module type Javascript file._

Several libraries can be added this way with no issues. And the nature of the error is complaining about syntax.

IPFS requires that I specify new instances of datastore-interfaces to specify where the Repo should be located for the app. I don't want it stuck in IndexedDB, I want to specify a on disk path to store the full node.

So according to https://github.com/ipfs/js-ipfs-repo/tree/master/packages/ipfs-repo#createrepopath-options

I have to specify the storage backends with instances of datastore-fs if I want the storage to take place on the file system.

**Comment by kthewhispers** [comment]
I just went with a js-ipfs daemon and bypassed interacting entirely with this lib.
