### ISSUE TITLE
Missing async dependency

### ISSUE THREAD

**Issue by paulogr** [ipfs/js-datastore-fs#9]
Hi folks, I just started with IPFS and installed the module `js-ipfs` in my application that has dependency with this module and got the error message bellow:

```
Error: Cannot find module 'async/setImmediate'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/paulogr/dev/projects/d-pagestatus/app/node_modules/datastore-fs/src/index.js:9:22)
```

Just saw that the `async`module is installed as `devDependencies` is your package.json file that might cause this error message.

Please, take a look, installing this as a runtime dependency solve the problem.

Thanks!

**Comment by richardschneider** [comment]
@paulogr Thanks, corrected in the above PR.
